# Generated by Django 3.2.16 on 2022-10-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aproved',
            new_name='approved',
        ),
    ]
